version: '3'
services:
  gateway:
    build: .
    ports:
     - "2525:2525"
    volumes:
      #- ./priv/conf/configuration.json:./priv/conf/configuration.json
      - ./dumps:/home/geo-gateway/_build/prod/rel/GeoGateway/dumps
      - ./logs:/home/geo-gateway/_build/prod/rel/GeoGateway/logs
